language: php
php:
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest"

before_script:
  - travis_retry composer self-update
  - travis_retry composer update $COMPOSER_FLAGS --no-interaction --prefer-dist --dev

script:
  - ./vendor/bin/phpmd src text ./ruleset.xml
  - ./vendor/bin/phpcs
  - ./vendor/bin/psalm
